---
- hosts: "{{ tomcat }}"
  become: yes
  vars:
  - warName: SinglePageApp.war
  - warRemotePath: /home/{{ansible_user}}
  - destDir: /usr/share/tomcat/webapps/SinglePageApp
  
  

  tasks:
  - name: Download WAR to server
    command: wget {{war_file_url}} -O {{ warRemotePath }}/{{ warName }}

  - name: Create destDir
    file: path="{{ destDir }}" mode=0755 state=directory    

    
  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest={{ destDir }} remote_src=yes
    register: zipfile 

  - name: Restart tomcat
    service: name=tomcat state=restarted


  - name: wait for tomcat to start
    wait_for: port=8080 timeout=60 
  
