---
- name: Azure VM
  hosts: localhost
  vars:
    public_ip: []
  tasks:
    - pip:
        name:
          - ansible-tower-cli
        extra_args: --user
        executable: pip3
      delegate_to: localhost
      
    - name: Define the backend configuration at init
      community.general.terraform:
        project_path: '../terraform/modules/provision_vm'
        state: present
        force_init: true
      register: terraform_output
      
    - debug: var=terraform_output
    
    - debug: var=terraform_output.outputs.public_ip_addresses.value
    
    - set_fact:
        public_ip: "{{ public_ip + [item]  }}"
      with_items: "{{ terraform_output.outputs.public_ip_addresses.value }}"
      
    - debug: var=public_ip
    
    - set_stats:
        data:
          tomcat: "{{ terraform_output.outputs.public_ip_addresses.value[0] }}"
          postgres: "{{ terraform_output.outputs.public_ip_addresses.value[1] }}"    

     
    - name: Add tower host
      tower_host:
        name: "{{ item }}"
        description: "Azure Inventory"
        inventory: "Azure Inventory"
        state: present
        tower_host: "{{ towerURL }}"
        tower_password: "{{ password }}"
        tower_username: "{{ userid }}"
      with_items: "{{ terraform_output.outputs.public_ip_addresses.value }}"
