---
- hosts: all
  become: yes
  tasks:
    - name: Install basic packages
      package:
        name: ['vim','aptitude','bash-completion','tmux','tree','htop','wget','unzip','curl','git']
        state: present
        update_cache: yes
