---
- name: Postgres role
  hosts: "{{ postgres }}"
  become: yes

  vars:
    - postgres_listen_addresses: "*"
    - postgres_client_auth:
      - type: host
        database: all
        user: all
        address: 0.0.0.0/0
        method: md5
      - type: local
        database: all
        user: all
        method: md5

  tasks:
    - name: Installing Postgress
      include_role: 
        name: ansible-role-postgres
        apply:
          delegate_to: "{{ ip }}"

  tags:
    - postgres
